# Generated by Django 5.2.10 on 2026-02-07 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='dog_name')),
                ('photo', models.ImageField(upload_to='dogs/')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth_date')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.breed', verbose_name='breed')),
            ],
            options={
                'verbose_name': 'dog',
                'verbose_name_plural': 'dogs',
            },
        ),
    ]
