# Generated by Django 5.2.11 on 2026-02-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_dog_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='views',
            field=models.ImageField(default=0, upload_to='', verbose_name='Просмотры'),
        ),
    ]
