# Generated by Django 5.2.11 on 2026-03-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='sign_of_review',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
    ]
