# Generated by Django 5.2.11 on 2026-03-03 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_slug'),
    ]

    operations = [
    ]
